name = "aaraa-forms"
main = "worker.js"
compatibility_date = "2024-11-01"

# Set secrets with:
#   wrangler secret put RESEND_API_KEY
#   wrangler secret put MAIL_FROM
#   wrangler secret put MAIL_TO
# Public vars below:
[vars]
ALLOWED_ORIGIN = "https://www.aaraainfrastructure.com"
